from time import sleep
print('Oi sou Leandro Coelho Da Silva *nome estranho eu sei* tenho 14 anos')
sleep(4)
print('Tenho muito que agradecer a vocês,Vocês me ajudaram nos meus códigos,Obrigado')
sleep(5)
print('Mural dos fodões:')
print('Vitor')
print('Esdras')
print('Cesar(Apesar de zoar skskks)')
print('Luiz')
print('Hiago')
print('Rukasu')
print('Não tô falando quem e mais foda,todos vocês são fodas')
sleep(8)
print('Agora farei 1 minuto de silencio ao respeito que tenho por vocês:')
for x in range(61):
    sleep(1)
    print(x)
print('Tô rindo muito kkkkkk sou mt besta kkk')
print('OBRIGADO PELA AJUDA GALERA')
